language: node_js
node_js:
  - 6
  - 4
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@latest
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - chmod +x scripts/docs
after_script:
  - npm run coverage
after_success:
 - scripts/docs
